### PR TITLE
SDK 34

### PR DESCRIPTION
**Pull request by Dhina17**

### CODE REVIEW

**Comment by HBiSoft** [comment]
Thank you for the pull request. I will have a look and test it later today.

**Comment by PodolianBohdan** [comment]
@HBiSoft hi, did you test it? when you update this?

**Comment by jerinjohnk** [comment]
After upgrading our targetSdkVersion to 34, HBRecorder has started crashing on Android 14. @HBiSoft, can you please check this PR?

**Comment by robrechtme** [comment]
Looks good to me, would be nice if this can get merged 🙂

**Comment by eliaslecomte** [comment]
Nice contribution @Dhina17!

I wonder if this is really how Android 14 intended us to use? What is the underlaying platform change that requires this? Could you link to the documentation?

```
Handler handler = new Handler(Looper.getMainLooper());
        mMediaProjection.registerCallback(new MediaProjection.Callback() {
            // Nothing
            // We don't use it but register it to avoid runtime error from SDK 34+.
        }, handler);
```

**Comment by mirjalal** [comment]
@HBiSoft when do you plan to merge these changes?

**Comment by HBiSoft** [comment]
@mirjalal 
Merged and is available in `3.0.2`

**Pull request merged**
